---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Gabriel's micro services

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

quicklaunch:
  # hideInternetSearch: true
  # hideVisitURL: true
  provider: google

cardBlur: md
useEqualHeights: true
headerStyle: clean
target: _self
statusStyle: 'dot'
hideErrors: true

# background:
#   image: https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?ixid=M3w1MjQwNDl8MHwxfHNlYXJjaHw5fHxiZWFjaHxlbnwwfDB8fHwxNzU5MDg1MjgxfDA&ixlib=rb-4.1.0
#   blur: md # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur

layout:
  Favorites:
    tab: Services
    style: row
    columns: 6
    disableCollapse: true
    header: false
  Home:
    tab: Services
    style: row
    columns: 4
  Photos:
    tab: Services
    style: row
    columns: 3
  Media:
    tab: Services
    style: row
    columns: 3
  Downloads:
    tab: Services
    initiallyCollapsed: true
  Storage:
    tab: Admin
    style: row
    columns: 3
  DNS:
    tab: Admin
    columns: 3
  Network:
    tab: Admin
    columns: 2
  Monitoring:
    tab: Admin
    style: row
    columns: 3
  Infrastructure:
    tab: Admin
    style: row
    columns: 3
