http:
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    auth:
      basicauth:
        users:
          - '{{env "BASIC_AUTH_USERNAME"}}:{{env "BASIC_AUTH_PASSWORD_HASH"}}'

    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        # STSSeconds: "315360000"

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/24"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers

  # External routes not on Docker network
  routers:
    pihole:
      rule: "Host(`pihole.app.gabriellundmark.com`)"
      middlewares:
        - addprefix-pihole
      service: pihole

    synology:
      rule: "Host(`dsm.app.gabriellundmark.com`)"
      service: synology

    unifi:
      rule: "Host(`unifi.app.gabriellundmark.com`)"
      service: unifi

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.1.3:80"
        passHostHeader: true

    synology:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5000"
        passHostHeader: true

    unifi:
      loadBalancer:
        servers:
          - url: "http://10.0.1.1"
        passHostHeader: true
