http:
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"

    auth:
      basicauth:
        users:
          - '{{env "AUTH_USERNAME"}}:{{env "AUTH_PASSWORD_HASH"}}'

    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/24"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers

  # External routes not on Docker network
  routers:
    pihole:
      rule: 'Host(`pihole.{{env "DOMAIN_NAME"}}`)'
      middlewares:
        - addprefix-pihole
        - secured
      tls: # leave empty when wildcard certs are setup tls: {}
        certResolver: myresolver
      service: pihole

    synology:
      rule: 'Host(`dsm.{{env "DOMAIN_NAME"}}`)'
      middlewares:
        - default-headers
      tls:
        certResolver: myresolver
      service: synology

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.1.3:80"
        passHostHeader: true

    synology:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5000"
        passHostHeader: true
