api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
      middlewares:
        - secured@file

providers:
  docker:
    # Strip stack name and set default route to container name
    defaultrule: 'Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.{{env "DOMAIN_NAME_APPS"}}`)'
  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: true
      storage: /letsencrypt/acme.json

serversTransport:
  insecureSkipVerify: true
