api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "home.gabriellundmark.com"
          - main: "app.gabriellundmark.com"
            sans:
              - "*.app.gabriellundmark.com"
      middlewares:
        - secured@file

providers:
  docker:
    # Strip stack name and set default route to container name
    defaultRule: 'Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.app.gabriellundmark.com`)'
  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: g.lundmark@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: joker

serversTransport:
  insecureSkipVerify: true
