api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    # Strip stack name and set default route to container name
    defaultrule: 'Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.{{env "DOMAIN_NAME"}}`)'
  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: "g.lundmark@gmail.com"
      storage: "/letsencrypt/acme.json"
