api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    addRoutersLabels: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: 'homeassistant.gabriellundmark.com'
          - main: 'plex.gabriellundmark.com'
          - main: 'app.gabriellundmark.com'
            sans:
              - '*.app.gabriellundmark.com'

providers:
  docker:
    # Strip stack name and set default route to service.app.gabriellundmark.com
    defaultRule: 'Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.app.gabriellundmark.com`)'
  file:
    filename: /dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: g.lundmark@gmail.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: joker

serversTransport:
  insecureSkipVerify: true
