x-common: &common
  restart: unless-stopped
  environment:
    PUID: 1026
    PGID: 100
    TZ: Europe/Stockholm

services:
  seerr:
    restart: unless-stopped
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      # No PGID/PUID supported, runs as 1000
      TZ: Europe/Stockholm
    volumes:
      - /volume1/docker/stack-arr/data/seerr/config:/app/config
    ports:
      - 5055:5055
    depends_on:
      - sonarr
      - radarr

  aurral:
    <<: *common
    container_name: aurral
    image: ghcr.io/lklynet/aurral:latest
    environment:
      DOWNLOAD_FOLDER: /mnt/downloads
    volumes:
      - /volume1/downloads:/app/downloads
      - /volume1/docker/stack-arr/data/aurral:/app/backend/data
    ports:
      - 3010:3001
    depends_on:
      - lidarr

  sabnzbd:
    <<: *common
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    volumes:
      - /volume1/docker/stack-arr/data/sabnzbd:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media
    ports:
      - 8090:8080

  gluetun:
    <<: *common
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      default:
        aliases:
          - qbittorrent
          - transmission
    environment:
      TZ: Europe/Stockholm
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ENDPOINT_IP: ${WG_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: ${WG_ENDPOINT_PORT}
      WIREGUARD_PUBLIC_KEY: ${WG_PUBLIC_KEY}
      WIREGUARD_PRIVATE_KEY: ${WG_PRIVATE_KEY}
      WIREGUARD_PRESHARED_KEY: ${WG_PRESHARED_KEY:-}
      WIREGUARD_ADDRESSES: ${WG_ADDRESSES}
      FIREWALL_OUTBOUND_SUBNETS: 172.16.0.0/12
    ports:
      - 8080:8080  # qbittorrent
      - 9091:9091  # transmission

  qbittorrent:
    <<: *common
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /volume1/docker/stack-arr/data/qbittorrent:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media

  transmission:
    <<: *common
    container_name: transmission
    image: linuxserver/transmission:latest
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /volume1/docker/stack-arr/data/transmission:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media

  sonarr:
    <<: *common
    container_name: sonarr
    image: linuxserver/sonarr:latest
    volumes:
      - /volume1/docker/stack-arr/data/sonarr:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media
    ports:
      - 8989:8989
    depends_on:
      - prowlarr
      - nzbhydra
      - sabnzbd
      - qbittorrent

  radarr:
    <<: *common
    container_name: radarr
    image: linuxserver/radarr:latest
    volumes:
      - /volume1/docker/stack-arr/data/radarr:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media
    ports:
      - 7878:7878
    depends_on:
      - prowlarr
      - nzbhydra
      - sabnzbd
      - qbittorrent

  bazarr:
    <<: *common
    container_name: bazarr
    image: linuxserver/bazarr:latest
    volumes:
      - /volume1/docker/stack-arr/data/bazarr:/config
      - /volume1/media:/media
    ports:
      - 6767:6767

  lidarr:
    <<: *common
    container_name: lidarr
    image: linuxserver/lidarr:latest
    volumes:
      - /volume1/docker/stack-arr/data/lidarr:/config
      - /volume1/downloads:/downloads
      - /volume1/music:/music
    ports:
      - 8686:8686
    depends_on:
      - prowlarr
      - nzbhydra
      - sabnzbd
      - qbittorrent

  nzbhydra:
    <<: *common
    container_name: nzbhydra
    image: linuxserver/nzbhydra2:latest
    volumes:
      - /volume1/docker/stack-arr/data/nzbhydra:/config
      - /volume1/downloads:/downloads
      - /volume1/media:/media
    ports:
      - 5076:5076

  prowlarr:
    <<: *common
    container_name: prowlarr
    image: linuxserver/prowlarr:develop
    volumes:
      - /volume1/docker/stack-arr/data/prowlarr:/config
    ports:
      - 9696:9696
